### ISSUE TITLE
Account for a name starting with a number when using the capitalize function

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#181]
To make plot labels look better the library uses `string.capitalize()` to capitalise the first character. However this throws and error if the first character or if a number is sent. Write a sub function that can handle the error thrown or test before running.

This occurred when a `.alpha` series from a shear object was sent to a distribution function.

**Comment by lucunnin** [comment]
I can't seem to recreate this issue. I see where string.capitalize() is being used and it seems to only be used on the 'aggregation method' string which should obviously never be a number. Also, string.capitalize() now seems to be able to simply ignore numbers at the beginning of a string anyway. This could be due to a recent package update or something? I have tried this with all the distribution functions. Example shown below:
![image](https://user-images.githubusercontent.com/46243826/68687560-6a215480-053b-11ea-985d-695aa1733e1a.png)

**Comment by stephenholleran** [comment]
Did you try it with a Shear obj.alpha timeseries?

**Comment by stephenholleran** [comment]
Did we update the shear.alpha series to have a name?

**Comment by lucunnin** [comment]
> Did you try it with a Shear obj.alpha timeseries?

Yes I have. I can't seem to find an issue with the capitalize().
![image](https://user-images.githubusercontent.com/46243826/68957629-6f2f0f80-0798-11ea-8290-8ff37b2c5856.png)


There is a different issue I am coming across relating to the datetime library when trying to do a dist_12x24() of a ShearTimeOfDay.alpha object, however. 
![image](https://user-images.githubusercontent.com/46243826/68957740-a8677f80-0798-11ea-88a3-7b38d6cd217c.png)

Will see what I can do about that too.

**Comment by lucunnin** [comment]
> Did you try it with a Shear obj.alpha timeseries?

Yeah, I can't seem to find an issue with capitalize(). See example below:
![image](https://user-images.githubusercontent.com/46243826/68957925-0f853400-0799-11ea-8a05-47b3d3e38af7.png)

There is a different issue, relating to the datetime library when trying to do a `dist_12x24()` with a ShearTimeOfDay.alpha DataFrame, I will look into that too. 
![image](https://user-images.githubusercontent.com/46243826/68958020-422f2c80-0799-11ea-9d3d-2b88b21210d8.png)

> Did we update the shear.alpha series to have a name since this issue was created?

We definitely did add a name to the shear.alpha series at some stage after the shear was included in the library so that could well be it.

**Comment by stephenholleran** [comment]
> There is a different issue, relating to the datetime library when trying to do a dist_12x24() with a ShearTimeOfDay.alpha DataFrame, I will look into that too.

Create a new issue for this one if there is an issue once you look into it.

**Comment by stephenholleran** [comment]
> We definitely did add a name to the shear.alpha series at some stage after the shear was included in the library so that could well be it.

Most likely so. You can close this so.
