### ISSUE TITLE
[Speedsort] synthesises windspeeds when there is no corresponding direction

### ISSUE THREAD

**Issue by ShaneBrightWind** [brightwind-dev/brightwind#227]
The syntheize function of speedsort appears in some cases just to return a windspeed but no direction value. When records checked, it seems to output a windspeed for every value of reference direction, even though in some cases this is not valid. 

![image](https://user-images.githubusercontent.com/32269199/80191943-5875ca00-860e-11ea-82da-47542b540093.png)

**Comment by BiancaMorandi** [comment]
@ShaneBrightWind I think that this issue is solved already in master...do you remember for which dataset did you generate this example?

if target and ref direction and target speed are nan but reference speed is not nan are you happy that synthesised target spd is nan? ie example below:
![image](https://user-images.githubusercontent.com/65398058/149822281-bd26ed2f-7e55-48f0-acfe-500005d370d7.png)

**Comment by ShaneBrightWind** [comment]
@BiancaMorandi I dont remember what dataset i used at the time. But have you tried it for the following situation?

1. No reference windspeed, But with a reference direction. Does it output a target windspeed in this case?

**Comment by BiancaMorandi** [comment]
@ShaneBrightWind Yes, see example below.
![image](https://user-images.githubusercontent.com/65398058/149909048-d8cbec45-0b91-40c6-a610-e52546299fa8.png)

**Comment by ShaneBrightWind** [comment]
Ok so if there is a reference direction it only produces a target direction and not a windspeed. Fine. Happy for you to close.
