### ISSUE TITLE
[export_tab_file] Small fix in tab file header sentence

### ISSUE THREAD

**Issue by BiancaMorandi** [brightwind-dev/brightwind#235]

**Comment by stephenholleran** [comment]
@BiancaMorandi 
Are we going to improve the print statement `print('Export of tab file successful.')` too?

Something like:
'Export of tab file _file_name_ successful. Mean wind speed derived from this ...................'

**Comment by stephenholleran** [comment]
![image](https://user-images.githubusercontent.com/25622575/84791470-8c57e500-afea-11ea-8abc-4c897b55a27e.png)


Can you put the file extension on the end of the filename? Maybe wrap it in a quote to separate it?

Can you put labels/units on the last line i.e. "Latitude: 53.00N, Longitude: -8.00E, Height: 80.00 m

I see you specify the decimals for the last line. What comes out otherwise? The least decimals the better. Why not just print what I typed in?
