### ISSUE TITLE
[twelve_by_24] update doc string and write tests

### ISSUE THREAD

**Issue by stephenholleran** [brightwind-dev/brightwind#57]
Update the doc string:

- [x] return is not just a DataFrame but is default a plot with DataFrame optional.

- [x] change 'var_name' to 'var_name_label' as this is the label that is applied to the legend. Makes it more intuitive about what 'var_name' will actually do.

- [x] :parm and :type for 'var_series' isn't well defined.

Write tests:

- [x] ??

**Comment by Inder95** [comment]
@stephenholleran For your perusal

**Comment by stephenholleran** [comment]
> Accepts a variable series and returns a plot of 12x24 (months x hours) table for the variable.

Change to something like this:
Accepts a variable series and returns a plot of 12x24 (12 months x 24 hours) for the 'mean' of the variable with the table of data as an optional return. The aggregation_method 'mean' can be can be changed as outlined below.

- [ ] Keep the doc string parameters in the same order as they are listed in the function itself. Makes it easier for the user to follow when trying to figure out what each parameter is for. Maybe return_data as the last one to be somewhat consistent with other functions.

- [ ] Can this return a count or frequency as well as the percentile?

- [ ] In the example usage can you give an example for when a function is passed for the aggregation method? Maybe write a test for this too?

**Comment by Inder95** [comment]
> > Accepts a variable series and returns a plot of 12x24 (months x hours) table for the variable.
> Change to something like this:
> Accepts a variable series and returns a plot of 12x24 (12 months x 24 hours) for the 'mean' of the variable with the table of data as an optional return. The aggregation_method 'mean' can be can be changed as outlined below.

Changed


> * [ ]  Keep the doc string parameters in the same order as they are listed in the function itself. Makes it easier for the user to follow when trying to figure out what each parameter is for. Maybe return_data as the last one to be somewhat consistent with other functions.

return_data moved to end as suggested

> * [ ]  Can this return a count or frequency as well as the percentile?

Can return count, added that to docstring but not frequency or percentile

> * [ ]  In the example usage can you give an example for when a function is passed for the aggregation method? Maybe write a test for this too?

Added

**Comment by stephenholleran** [comment]
> > * [x]   Can this return a count or frequency as well as the percentile?
> 
> Can return count, added that to docstring but not frequency or percentile

To me count and frequency are the same thing.
Should we add percentile so? In other distribution functions we use '%frequency' to calculate percentages. What do you think?

**Comment by Inder95** [comment]
I have added '%frequency'  but the graphs here are not very interesting as most of the hours for most months must have almost same number of  data points. If there is any other way to implement '%frequency' let me know.
![image](https://user-images.githubusercontent.com/23189856/58715514-ecb7bc80-83be-11e9-909e-85c4f163b30a.png)


For percentile I think we should pass on that because then we have to add additional variable to pass the percentile. Though I will check whether I can add an example of a custom aggregation function implementing percentile aggregation.

@stephenholleran ?

**Comment by stephenholleran** [comment]
Yeah, I agree, I don't think it actually relevant for a 12x24. It is more relevant for a distribution matrix.

Why has the top colour bar change from dark to light at 0.365?

The chart title is 'Hourly Mean Calendar Month'. What does that mean if 'sum' was sent?

**Comment by Inder95** [comment]
- I have left the %frequency there as we have already coded it.
- Good observation, there was a problem the way we were deciding levels, its fixed now.
- When sum or any other thing is sent that will replace the mean in plot title from now

![image](https://user-images.githubusercontent.com/23189856/58827478-09602880-863b-11e9-8bd9-1ba4392f0e6e.png)

**Comment by stephenholleran** [comment]
Hey, doesn't seem to work for me at all.
```python
TypeError: len() of unsized object
```
'levels' used to be an array and now its an integer?

![image](https://user-images.githubusercontent.com/25622575/58915661-6d591e80-8719-11e9-9218-623a6d61e32f.png)


I'll check out count and %frequency when it works but it might be best to remove it as all it does is show coverage.

**Comment by Inder95** [comment]
Works for me, I am using matplotlib 3.0.3. Updated the version in requirements.
Levels can be an integer too, matplotlib then automatically calculates levels for us. The method we were using earlier caused more than 7 levels when we were using only 7 colors. Hence earlier you saw a lighter color after a dark one.
I will remove both of them

![image](https://user-images.githubusercontent.com/23189856/58983638-32192700-87cf-11e9-9a2b-914e7ee64e48.png)

**Comment by stephenholleran** [comment]
@Inder95 I did some refactoring of the labels. Make sure it is all ok.

Also, plotting T2M from the campbell data and the 'max' plot colours are off. There are no values in the table below 7.5 but yet there is a colour for it. And of course the top colour is light.

![image](https://user-images.githubusercontent.com/25622575/59069979-e9399f00-88b0-11e9-9740-bca89770e4ac.png)
![image](https://user-images.githubusercontent.com/25622575/59069988-f6568e00-88b0-11e9-9b07-7900edccee2a.png)

**Comment by stephenholleran** [comment]
What happens when we don't have a full year of data? It looks like the plot doesn't plot the months in the correct place as the x ticks are just an array and not linked to the data.

**Comment by Inder95** [comment]
There was a bug in matplotlib itself. Setting levels as int in contourf() does not give the number of levels specified as described by their documentation (https://matplotlib.org/3.0.3/api/_as_gen/matplotlib.axes.Axes.contourf.html#matplotlib.axes.Axes.contourf). The way around this problem was to manually create levels by taking max and min of the 12x24 table and creating 8 bins.

As per the values, they are less than 7.5 in column 4

The contourf() function automatically picks x axis from `table_12x24`, but I have now explicitly passed the months and hours as x and y axes, to avoid confusion. As per the x-axis wrongly labelled 
![image](https://user-images.githubusercontent.com/23189856/59149875-48afc000-8a13-11e9-9761-630378322e4d.png)

The thing about the case when a whole year is not sent was a good change, the xticklabels were changed to solve that issue.
![image](https://user-images.githubusercontent.com/23189856/59150130-97128e00-8a16-11e9-94c3-7c0c52263d45.png)

**Comment by stephenholleran** [comment]
Great stuff!
